[tool.poetry]
name = "two-qubit-transmno-auto-tuning"
version = "0.1.0"
description = ""
authors = ["Joel Pendleton <joelkieronpendleton@gmail.com>"]
readme = "README.md"
packages = [{include = "two_qubit_transmno_auto_tuning"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
